openapi: 3.0.1
info:
  title: Products API
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Get a list of products
      description: Retrieves a list of available products.
      responses:
        "200":
          description: List of products retrieved successfully
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
        "404":
          description: Not found, product or resource does not exist
        "500":
          description: Internal server error, something went wrong
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          description: Number of items per page
          schema:
            type: integer
      tags:
        - Products
    post:
      summary: Create a new product
      description: Creates a new product in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product created successfully
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
        "500":
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Products

  /api/products/addproducts:
    get:
      summary: Access to the page for adding products
      description: Provides access to the page for adding new products.
      responses:
        "200":
          description: Add products page loaded successfully
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
      security:
        - jwt: []
      tags:
        - Products

    post:
      summary: Add a new product
      description: Adds a new product to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product added successfully
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
        "500":
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Products

  /api/products/listproducts:
    get:
      summary: Get a list of products (with pagination)
      description: Retrieves a paginated list of available products.
      responses:
        "200":
          description: List of products retrieved successfully
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
        "500":
          description: Internal server error, something went wrong
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          description: Number of items per page
          schema:
            type: integer
      tags:
        - Products

  /api/products/{pid}:
    get:
      summary: Get a product by its ID
      description: Retrieves a specific product by its ID.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product being requested
          schema:
            type: string
      responses:
        "200":
          description: Product retrieved successfully
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
        "404":
          description: Not found, product does not exist
        "500":
          description: Internal server error, something went wrong
      tags:
        - Products
    put:
      summary: Update a product by its ID
      description: Updates a specific product by its ID.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product being updated
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product updated successfully
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
        "404":
          description: Not found, product does not exist
        "500":
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Products
    delete:
      summary: Delete a product by its ID
      description: Deletes a specific product by its ID.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product being deleted
          schema:
            type: string
      responses:
        "200":
          description: Product deleted successfully
        "400":
          description: Bad request, invalid parameters
        "401":
          description: Unauthorized, authentication required
        "403":
          description: Forbidden, insufficient permissions
        "404":
          description: Not found, product does not exist
        "500":
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Products
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Autogenerated Id in Mongo
        title:
          type: string
          description: Title of the product
        description:
          type: string
          description: Description of the product
        price:
          type: number
          description: Products price
        stock:
          type: integer
          description: Products Stock
        category:
          type: string
          description: Products Category
        thumbnail:
          type: string
          description: Thumbnail URL for the product
        owner:
          type: string
          description: User that create this product
        code:
          type: string
          description: Code to identify products
        status:
          type: boolean
      example:
          _id: 65302b57119af044fd064873
          title: Beef - Inside Round
          description: Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.
          code: 993887463-0
          price: 5876.21
          status: true
          stock: 769
          category: Pets
          thumbnail: http://dummyimage.com/196x100.png/dddddd/000000
          owner: suanairiarte@gmail.com
