openapi: 3.0.1
info:
  title: Cart API
  version: 1.0.0
paths:
  /api/cart:
    post:
      summary: Create a new cart
      description: Creates a new shopping cart.
      responses:
        '201':
          description: Cart created successfully
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
  /api/cart/user:
    get:
      summary: Get user's cart
      description: Retrieves the shopping cart associated with the user.
      responses:
        '200':
          description: User's cart retrieved successfully
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
  /api/cart/pid/{pid}:
    get:
      summary: Add a product to the cart by ID
      description: Adds a product to the user's cart by its ID.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product to add to the cart
          schema:
            type: string
      responses:
        '200':
          description: Product added to the cart successfully
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
  /api/cart/delete/{pid}:
    get:
      summary: Delete a product from the cart by ID
      description: Deletes a product from the user's cart by its ID.
      parameters:
        - name: pid
          in: path
          required: true
          description: ID of the product to delete from the cart
          schema:
            type: string
      responses:
        '200':
          description: Product deleted from the cart successfully
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
  /api/cart/{cid}/product/{pid}:
    put:
      summary: Update product quantity in the cart
      description: Updates the quantity of a product in the user's cart.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID of the user's cart
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID of the product in the cart
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Product quantity in the cart updated successfully
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
  /api/cart/{cid}:
    get:
      summary: Get a cart by ID
      description: Retrieves a specific shopping cart by its ID.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID of the cart being requested
          schema:
            type: string
      responses:
        '200':
          description: Cart retrieved successfully
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
  /api/cart/{cid}/products/{pid}:
    post:
      summary: Add a product to the cart by ID with role restrictions
      description: Adds a product to the user's cart by its ID with role-based access restrictions.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID of the user's cart
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID of the product to add to the cart
          schema:
            type: string
      responses:
        '200':
          description: Product added to the cart successfully with role restrictions
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
  /api/cart/{cid}/purchase:
    get:
      summary: Purchase cart and create a ticket
      description: Completes the purchase of items in the user's cart and creates a ticket.
      parameters:
        - name: cid
          in: path
          required: true
          description: ID of the user's cart
          schema:
            type: string
      responses:
        '200':
          description: Cart purchased successfully, and a ticket created
        '500':
          description: Internal server error, something went wrong
      security:
        - jwt: []
      tags:
        - Cart
components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the cart.
        user:
          type: object
          description: The user associated with the cart.
        products:
          type: array
          description: The list of products in the cart.
          items:
            type: object
            properties:
              pid:
                type: string
                description: The unique identifier of the product in the cart.
              quantity:
                type: integer
                description: The quantity of the product in the cart.